ParetoSecurity/agent

- test/integration/nixos.nix
Remove old project name from nixos tests systemd service/timer unit names.
Note: these units are not actually used in the test as far as I can tell. Or maybe `Persistent=true` does that. In any case,`nixos.py` runs `paretosecurity check` directly.
> chore(test): update systemd unit names

- apt/paretosecurity.socket
- shared/socket.go
- test/integration/nixos.nix
/var/run/ is obsolete socket path fur running app in systemd.
> fix: update socket path from /var/run to /run in configuration and code

- .github/workflows/unit.yml
- .gitignore
- checks/linux/firewall.go
- checks/linux/firewall_test.go
- flake.lock
- flake.nix
- test/integration/README.md
- test/integration/firewall.nix
Before this, if there is no firewall, the check was skipped. Now it fails.
> Firewall check should fail if no firewall is found

- .github/workflows/unit.yml
- checks/linux/password_unlock.go
- checks/linux/password_unlock_test.go
- flake.nix
- test/integration/common.nix
- test/integration/screenlock.nix
- Make Screen lock check verify all installed desktop environments that are supported - (e.g. user has both GNOME and KDE installed so both should be verified).
- Add integration tests for Screen lock.
Ref: https://github.com/teamniteo/pareto/issues/643
> Add NixOS Integration test for Screen lock

- flake.lock
- flake.nix
- package.nix
So that we can get the latest package definition from nixpkgs and can remove local fixes.
> cleanup: Upgrade nixpkgs

- flake.nix
Recent changes to nixpkgs have broken the NixOS tests on Mac: https://github.com/NixOS/nixpkgs/commit/72155225aa62c6ac9bc67a1253079f140045511f#commitcomment-156643558
This commit works around the changes to restore running the NixOS tests on Mac:
```
$ nix build .#checks.aarch64-darwin.firewall
```
Refs https://github.com/tfc/nixos-integration-test-example/issues/1
> fix: Un-break NixOS Tests on Mac

- .github/workflows/build.yml
- checks/linux/firewall.go
- checks/linux/firewall_test.go
- test/integration/firewall.nix
As of recently, many firewall frontends have moved to using nftables instead of iptables. This commit adds support for detecting if nftables are used as a fiewall implementation.
Refs https://github.com/ParetoSecurity/agent/issues/39
> feat: Add support for nftables

- devenv.nix
After upgrading to latest version in nixpkgs, some Go tests started failing, because we apparently did not run Go unit tests in CI?
For this to not happen again, we now run `nix build` in our unit test CI action, so that Go tests are run as part of the nix build.
> Fix failing nix build

- checks/linux/password_unlock.go
- checks/linux/password_unlock_test.go
ref: https://github.com/ParetoSecurity/agent/issues/129
> fix: rename checkKDE to checkKDE5 and add checkKDE6 for improved KDE support

- checks/linux/password_manager.go
- checks/linux/password_manager_test.go
It would be better to detect usage of  `org.freedesktop.secrets` so that the check has a more generic password manager detection, but let's not let perfect be the enemy of good and do the refactor at a later point: https://github.com/teamniteo/pareto/issues/712
cc @domenkozar
> feat: Add support for gnome-keyring password manager

- checks/linux/password_unlock.go
- checks/linux/password_unlock_test.go
- shared/home.go
- test/integration/screenlock.nix
KDE has very dubious command-line usage, where "--default" defaults to whatever is specified, and not the actual configured value. This is because some states are defaulted in runtime but never persisted in files. With this patch we test for absence of configuration that would turn off the screen lock on resume.
ref: https://github.com/ParetoSecurity/agent/issues/129
> feat: refactor KDE check logic to read configuration file directly

- flake.lock
- flake.nix
Nix-vm was replaced by incus and docker tests.
> refactor: Remove nix-vm-test dependency and related code from flake.nix

- .github/workflows/nix-check-test.yml
- .goreleaser.yaml
- cmd/trayicon.go
- cmd/trayicon_test.go
- flake.nix
- test/integration/trayicon.nix
- This will now open the documentation page on launch if the `trayicon` package is not installed.
- Since there is no optional dependency support that would install the indicator extension only if GNOME is present, we recommend the package. This is handled differently on each variant of distribution, sometimes with a console notice, sometimes with an alert, or nothing.
> feat(trayicon): Add support check for StatusNotifierWatcher and error handling

- cmd/paretosecurity-tray/main.go
- cmd/paretosecurity/main.go
- cmd/trayicon.go
- go.mod
- go.sum
- package.nix
Checks, link, and unlink must run concurrently and have no issues doing so. The only annoying part is the tray icon, so this adds support for only one instance to it.
ref: https://github.com/teamniteo/pareto/issues/737
> feat: Add single instance lock for tray applications

- checks/linux/application_updates.go
- checks/linux/application_updates_test.go
Enhance the update check logic for Flatpak applications and ensure that root access is required for performing update checks.
> Require root access for Linux application updates and simplify update check logic

- checks/linux/firewall.go
- checks/linux/firewall_test.go
Firewall is active if:
1. The default policy is restrictive (DROP/REJECT), OR
2. There are explicit DROP/REJECT rules in the INPUT chain, OR
3. There's a custom chain AND it's a known firewall chain (nixos-fw, ufw-, etc)
ref: https://github.com/ParetoSecurity/agent/issues/39
> Refine firewall detection logic

- apt/paretosecurity.service
Removed installation section and added timeout setting to be compatible with systemd 259+.
> Modify paretosecurity.service configuration

- .github/workflows/win-vm.yml
Refs https://github.com/teamniteo/pareto/issues/812
> Easily spin up a Windows 11 VM on Azure for testing things out

- shared/device_all.go
- shared/device_windows_test.go
Windows 11 reports itself as Windows 10 to maintain compatibility with legacy applications. We have to look into `buildNumber` to differentiate between Windows 10 and Windows 11.
Refs https://github.com/teamniteo/pareto/issues/811
> Improve Windows version detection

- checks/linux/password_unlock.go
- checks/linux/password_unlock_test.go
- test/integration/screenlock.nix
Ref: https://github.com/ParetoSecurity/agent/issues/129
> feat: support sway+swaylock for screen saver lock check

- flake.nix
- team/report.go
Cloud app no longer require this timestamp.
Ref: https://github.com/teamniteo/pareto/issues/723
> chore: stop sending LastCheck timestamp
