.github/workflows/build.yml
flake.nix
test/integration/nixos.py

ref: https://github.com/ParetoSecurity/pareto-linux/issues/5

refactor: Simplify NixOS test configuration and add service management

---

checks/ssh_config.go
checks/ssh_keys.go

ref: https://github.com/ParetoSecurity/pareto-linux/issues/25

refactor: Enhance SSH configuration checks and improve error handling

---

check/check.go
check/const.go
checks/autologin.go
checks/autologin_test.go
checks/docker.go
checks/firewall.go
checks/firewall_test.go
checks/kernel.go
checks/luks.go
checks/secure_boot.go
checks/ssh_config.go
cmd/helper.go
package.nix
shared/command.go
shared/os.go
shared/os_test.go
shared/socket.go
team/link.go
test/integration/debian.py
test/integration/nixos.py
test/integration/ubuntu.py

Adds tests for the firewall and autologin; creates a test harness for system operations and makes failures more detailed in CLI.

refactor: Consolidate file reading and enhance status reporting in checks

---

checks/darwin/password_manager.go
checks/darwin/password_manager_test.go
checks/linux/password_manager.go
checks/linux/password_manager_test.go
checks/windows/mock.go
checks/windows/password_manager.go
checks/windows/password_manager_test.go
claims/checks_darwin.go
claims/checks_linux.go
claims/checks_windows.go
devenv.lock
shared/cache.go
test/integration/nixos.py

Add checks for the presence of password managers on Windows, Mac, and Linux.

feat: Add check for password manager presence on Windows, Mac, and Linux

---

modules/paretosecurity.nix

Ref: https://github.com/ParetoSecurity/pareto-core/issues/40

Fix use of lib functions

---

checks/shared/pareto_updated_test.go
checks/shared/ssh_keys_algo_test.go
checks/shared/ssh_keys_test.go

ref: https://github.com/teamniteo/pareto/issues/593

feat: add unit tests for ParetoUpdated and SSHKeysAlgo components

---

checks/shared/pareto_updated.go
checks/shared/pareto_updated_test.go

I fix typo

---

checks/linux/application_updates.go
checks/linux/application_updates_test.go
claims/checks_darwin.go
claims/checks_linux.go
claims/checks_windows.go

Ref: https://github.com/teamniteo/pareto/issues/578

chore: rename Software to Application Updates

---

cmd/helper.go
cmd/helper_test.go

Rewrites test that simulates systemd with just connection handling.

refactor: improve error logging in runHelper and rewrite tests

---

cmd/check.go
runner/checks.go
shared/lastState.go

ref: https://github.com/teamniteo/pareto/issues/577#issuecomment-2731086505

refactor: implement check failure handling and improve state management

---

checks/linux/firewall.go
checks/linux/firewall_test.go

ref: https://github.com/ParetoSecurity/agent/issues/39

feat: add iptables check to firewall functionality

---

checks/linux/docker.go
checks/linux/docker_test.go

ref: https://github.com/ParetoSecurity/agent/issues/23#issuecomment-2746378374

fix: enhance Docker access checks for installation and daemon access

---

checks/linux/firewall.go
checks/linux/firewall_test.go

ref: https://niteo.slack.com/archives/C027Y87PKNY/p1742843797697259

fix: include iptables check in firewall runnable status

---

.goreleaser.yaml
apt/paretosecurity-trayicon.service
apt/paretosecurity-user.service
apt/paretosecurity-user.timer
apt/paretosecurity.service
apt/paretosecurity.socket
apt/postinstall.sh

This makes it easier to use in other distros, such as NixOS.
Refs https://github.com/teamniteo/pareto/issues/638

Move systemd configuration into files

---

apt/postinstall.sh

This will start the services when user logins. We can also add this as a toggle to the UI in systray.

feat: enable user services in post-install script

---

runner/checks.go

This is a bit out of spec, but we treat the check status as program output. All other logs stil go to stderr.

fix: replace default logger with checkLogger for improved logging in Check function

---

cmd/info.go
cmd/status.go
go.mod
go.sum
package.nix
shared/lastState.go

ref: https://niteo.slack.com/archives/D072GKGQP/p1742990414836199

feat: add status command to print the status of the checks

---

.github/copilot-instructions.md
cmd/menubar.go
shared/command.go
systemd/shared.go
systemd/timer.go
systemd/timer_test.go
systemd/tray.go
systemd/tray_test.go

ref: https://github.com/ParetoSecurity/agent/issues/167#issuecomment-2757333086

feat: add systemd timer management for background checks

---

checks/linux/firewall.go
checks/linux/luks.go
checks/linux/ssh_config.go
shared/socket.go

Refs https://github.com/ParetoSecurity/agent/issues/54#issuecomment-2760009295

Be more clear about root helper

---

checks/linux/firewall.go
checks/linux/firewall_test.go
test/integration/firewall.nix

Refs https://github.com/ParetoSecurity/agent/issues/39#issuecomment-2760762655

Fix firewall check to correctly detect for custom chains, such as `nixos-fw`

---

checks/linux/ssh_config.go

ref: https://github.com/ParetoSecurity/agent/issues/131

fix: improve SSH service check with status message

---

cmd/menubar.go
cmd/trayicon.go
go.mod
go.sum
package.nix
shared/last_state.go
shared/last_state_test.go

ref: https://github.com/ParetoSecurity/agent/issues/176

feat: Refresh menubar on state change

---

.github/workflows/integration-test.yml
checks/linux/password_manager.go
checks/linux/password_manager_test.go
flake.nix
test/integration/pwd-manager.nix

Ref: https://github.com/teamniteo/pareto/issues/644

Password manager check: nix support and tests

---

cmd/config.go
runner/checks.go
shared/config.go
shared/config_test.go

ref: https://github.com/teamniteo/pareto/issues/650?notification_referrer_id=NT_kwDOAAOnmbIxNTU4ODAwNDU2MjoyMzk1MTM&notifications_query=is%3Aunread#issuecomment-2765958893

feat: add support for disabling specific checks via configuration

---

.github/workflows/integration-test.yml
flake.nix
test/integration/secureboot.nix

Refs https://github.com/teamniteo/pareto/issues/647

Add secureboot integration test

---

checks/linux/firewall.go
checks/linux/password_manager.go
checks/linux/password_manager_test.go
flake.lock
flake.nix
package.nix

This means we don't have to manually duplicate:
* ingesting apt/*.service files
* fixing PATH for systemd services

Get package definition from nixpkgs

---

checks/linux/docker.go
checks/linux/docker_test.go

ref: https://github.com/ParetoSecurity/agent/issues/41

Add check for deprecated docker.io package in DockerAccess

---

checks/windows/automatic_updates.go
checks/windows/automatic_updates_test.go
checks/windows/defender.go
checks/windows/defender_test.go
checks/windows/firewall.go
checks/windows/firewall_test.go
claims/checks_windows.go
shared/command_unix.go
shared/command_windows.go
shared/device_all.go
shared/device_windows.go

ref: https://github.com/teamniteo/pareto/issues/653#issuecomment-2804861975

Add essential Windows checks

---

cmd/check.go
cmd/config.go
cmd/info.go
cmd/link.go
cmd/root.go
cmd/status.go
cmd/unlink.go
cmd/update.go
notify/notify_darwin.go
notify/notify_linux.go
notify/notify_windows.go
test/integration/help.nix

Refactor the error handling to use Fatal function instead of terminating the program with os.Exit calls.

Improve error handling and remove os.Exit calls

---

.github/workflows/release.yml
.goreleaser.yaml
checks/shared/pareto_updated.go
cmd/paretosecurity-tray/main.go

Let start first by adding required headers, before we enable full blown cache.
ref:https://github.com/ParetoSecurity/agent/issues/175

Pass proper headers for Github requests

---

.gitignore
default.nix
flake.lock
flake.nix

* drop non-flake support
* remove old flake check leftovers
* remove unused imports
Refs https://github.com/teamniteo/pareto/issues/641

Cleanup nix stuff

---

.github/workflows/release.yml
cmd/paretosecurity-tray/main.go
devenv.nix
go.mod
shared/config.go
shared/last_state.go
trayapp/format.go
trayapp/format_test.go
trayapp/icon.go
trayapp/tray.go
trayapp/watcher.go

- Fix tray would never update becase of earyl return from state watcher
- Prevent win11 bug on right click if title is set
- Properly populate initial state for claims
- Nicely format last update time

feat: Systray fixes

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/build.yml
apt/install.sh

ref: https://github.com/ParetoSecurity/agent/issues/236

refactor: Rewrite installation script based on best practice

---

shared/device_all.go
shared/string.go
shared/string_test.go

ref: https://niteo.slack.com/archives/C027Y87PKNY/p1747250663301169

fix: Sanitize serial numbers to remove non-ASCII characters

---

cmd/check.go
runner/checks_runner.go
runner/checks_runner_test.go
runner/root_runner.go

ref: https://github.com/teamniteo/pareto/issues/614#issuecomment-2883647272

fix: Add check for root helper service status in check command

---

.goreleaser.yaml
apt/install.sh
apt/postinstall.sh
cmd/check.go
runner/root_runner.go

- Moves repo install to initial step
- Removes unsigned packages from Github release

fix: update installation scripts for improved compatibility

---

.github/workflows/distro.yml
apt/postinstall.sh
flake.nix
test/integration/README.md
test/integration/cli.nix
test/integration/common.nix

Add smoke tests for different Linux distros

---

checks/shared/pareto_updated.go
checks/shared/pareto_updated_test.go

ref: https://github.com/teamniteo/pareto/issues/697#issuecomment-2894888044

fix: refactor version checking logic and add 10 day delay

---

checks/shared/pareto_updated.go
shared/http.go
team/report.go

Makes it esier to trace what client made what request.

fix: implement User-Agent header using shared.UserAgent() function

---

.goreleaser.yaml
checks/shared/pareto_updated.go
cmd/link.go
cmd/toast.go
go.mod
go.sum
notify/notify_darwin.go
notify/notify_linux.go
notify/notify_windows.go
package.nix
shared/updater.go
team/report.go
trayapp/tray.go

ref: https://github.com/teamniteo/pareto/issues/708

fix: add context with timeout to prevent hangs

---

checks/linux/application_updates.go
checks/linux/application_updates_test.go

ref: https://github.com/teamniteo/pareto/issues/709

fix: enhance flatpak update check to parse application and version details

---

.github/workflows/release.yml
apt/conf/options

ref: https://niteo.slack.com/archives/C027Y87PKNY/p1748514136195039

feat: add GPG signing for RPM packages in release workflow

---

trayapp/tray.go

Refs https://github.com/teamniteo/pareto/issues/715#issuecomment-2929965381

Link errored checks to docs/linux/check-error

---

.github/workflows/nix-check-test.yml
flake.nix
test/integration/common.nix
test/integration/desktop/xfce.nix

add: xfce desktop manager test

---

.gitignore
cmd/paretosecurity-tray/main.go
cmd/paretosecurity/main.go
cmd/trayicon.go
go.mod
go.sum
package.nix
trayapp/implementation.go
trayapp/interfaces.go
trayapp/tray.go
trayapp/tray_test.go
trayapp/utils.go

ref: https://github.com/teamniteo/pareto/issues/738

feat(trayapp): Introduce interfaces for dependency injection and improve testability

---

cmd/link.go
cmd/link_test.go

ref: https://github.com/teamniteo/pareto/issues/748

feat(link): support linking with team UUID and email

---

CLAUDE.md
devenv.nix
flake.nix
statix.toml
test/integration/autologin.nix
test/integration/cli.nix
test/integration/common.nix
test/integration/desktop/xfce.nix
test/integration/firewall.nix
test/integration/help.nix
test/integration/luks.nix
test/integration/pwd-manager.nix
test/integration/screenlock.nix
test/integration/secureboot.nix
test/integration/trayicon.nix

Replace alejandra with the official nix formatter. Add deadnix and statix.

Better linting

---

checks/linux/docker.go
checks/linux/docker_test.go

ref: https://github.com/teamniteo/pareto/issues/815

feat: enhance Docker access checks for installation and daemon access
